### PR TITLE
add github action CI

### PR DESCRIPTION
**Pull request by arvidn**

### CODE REVIEW

**Comment by richardkiss** [comment]
The "very deep tree" test segfaults here. I'm seen this before locally, and doing `maturin develop --release` fixes it for some reason. I suspect there is a genuine problem here.

**Comment by richardkiss** [comment]
Looks like the rust stack blows up trying to drop the tree of `Arc` items. My guess is that `--release` turns the tail recursion into a loop.

**Comment by arvidn** [comment]
yeah, either tail-recursion or release mode just making a lot smaller stack frames

**Comment by richardkiss** [comment]
Can you run `cargo fmt` on this & amend?

**Pull request merged**
